;/* Version 0f18582aadae64fbc73c6dcb04bb96c6 v:4.5.9.2098, c:3256481e937cf611d06fcbdf9e565a27826c9df6, b:4.5.9.2098 */(function(){/*


 Copyright (c) 2013, AppDynamics, Inc. All rights reserved.

 Derivative of Google Episodes:

 Copyright 2010 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 See the source code here:
 http://code.google.com/p/episodes/
*/
new function(){var g=window.ADRUM;if(g&&g.q&&!0!==window["adrum-disable"]){var A=window.console,y=A&&"function"==typeof A.log?A:{log:function(){}},u=this&&this.gc||function(){var d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(d,a){d.__proto__=a}||function(d,a){for(var b in a)a.hasOwnProperty(b)&&(d[b]=a[b])};return function(h,a){function b(){this.constructor=h}d(h,a);h.prototype=null===a?Object.create(a):(b.prototype=a.prototype,new b)}}();(function(d){(function(h){h.za=function(a){function b(d){return d.replace(/\s/g,
"")===e}var k={a:[1,2,3,"str"]},e='{"a":[1,2,3,"str"]}';if("undefined"!==typeof JSON&&JSON&&h.isFunction(JSON.stringify)&&b(JSON.stringify(k)))return JSON.stringify(a);if("undefined"!==typeof Object&&Object&&h.isFunction(Object.toJSON)&&b(Object.toJSON(k)))return Object.toJSON(a);d.error("M188");return null};h.wc=function(a,b,k){var e=a,c=k;"xhr"===k&&(e=document.createElement("div"),a.appendChild(e),c="xhr_"+a.getElementsByTagName("div").length);a=document.createElement("p");a.innerHTML="Script loaded from "+
d.conf.adrumExtUrl+". Metrics collected are:";e.appendChild(a);a=document.createElement("table");a.id="ADRUM_"+c;var c=document.createElement("tbody"),f;for(f in b){k=document.createElement("tr");var h=document.createElement("td");h.innerHTML=f;h.className="name";var m=document.createElement("td");m.innerHTML=String(b[f]);m.className="value";k.appendChild(h);k.appendChild(m);c.appendChild(k)}a.appendChild(c);e.appendChild(a)};h.dumpObject=function(){function d(b,k){try{if("object"!=typeof b)return String(b);
if(0<=h.wb(k,b))return"Already visited";k.push(b);var e;if(h.isArray(b)){for(var c="[ ",f=0;f<b.length;f++)0!=f&&(c+=", "),c+=d(b[f],k);e=c+" ]"}else{var c="{ ",f=!0,l;for(l in b)f?f=!1:c+=", ",c+=d(l,k)+" => "+d(b[l],k);e=c+" }"}return e}catch(m){return"dumpObject failed: "+m}}return function(b){return d(b,[])}}();h.wb=h.isFunction(Array.prototype.indexOf)?function(d,b){return d.indexOf(b)}:function(d,b){for(var k=0;k<d.length;k++)if(d[k]==b)return k;return-1};h.compareWindows=function(d,b){return d==
b};h.Gc=function(d,b,k,e,c){if(!h.isDefined(b))return b;if(h.isArray(b)){d=[];for(var f=0,l=b.length;f<l;f++)d[f]=h.Gc(f,b[f],k,e,c);return d}if(h.isFunction(b))return b;if(h.isObject(b)){d={};for(f in b)h.hasOwnPropertyDefined(b,f)&&(d[k(f)]=c&&c(f)?b[f]:h.Gc(f,b[f],k,e,c));return d}return e(d,b)};h.Wk=function(d){var b=[],k;for(k in d)h.hasOwnPropertyDefined(d,k)&&b.push([k,d[k]]);return b};h.gm=function(){try{localStorage.setItem("try","try");var d=localStorage.getItem("try");localStorage.removeItem("try");
return"try"===d}catch(b){return!1}};h.fm=function(){try{var d=h.za({v:1});return 1===JSON.parse(d).v}catch(b){return!1}};h.hm=function(){return h.isFunction(window.postMessage)};h.Si=function(d,b){var k=document.createElement("div");k.innerHTML='<iframe id="'+b+'" src='+d+' width="0" height="0" tabindex="-1" title="empty" style="display: none;"></iframe>';document.body.appendChild(k);return document.getElementById(b)};h.hg=function(d,b){h.isDefined(b)&&(d.parentPageName=b)};h.Oc=function(d){return h.isNumber(d)&&
isFinite(d)&&Math.floor(d)===d};h.ve=function(h){d.log(h);y.log(h)}})(d.utils||(d.utils={}))})(g||(g={}));(function(d){(function(d){d.tg=function(d){return/^[0-9]+$/.test(d)?Number(d):null};d.ef=function(d){return"number"===typeof d&&!isNaN(d)&&isFinite(d)}})(d.utils||(d.utils={}))})(g||(g={}));(function(d){(function(h){function a(c){var e=c.split("\r\n"),k=/^\s*ADRUM_(\d+): (.+)\s*$/i;c=[];for(var b=0;b<e.length;b++){var h=e[b];try{var a=k.exec(h);a&&c.push([Number(a[1]),a[2]])}catch(g){d.exception(g,
"M191",h)}}Array.prototype.sort.call(c,function(d,c){return d[0]-c[0]});a=[];for(e=0;e<c.length;e++)a.push(c[e][1]);return a}var b=d.utils.hasOwnPropertyDefined,k=null,e=null;h.Te=function(){e||(e=h.Af(h.Zc(h.cookieMetadataChunks),h.Zc(d.footerMetadataChunks)));return e};h.getPageGUID=function(){var c=d.monitor.DOMEventsMonitor,e=d.utils.isObject(c.currentBasePage)&&d.utils.isFunction(c.currentBasePage.guid);if(!k){var b=h.Te();k=b&&b.clientRequestGUID||(e?c.currentBasePage.guid():d.utils.generateGUID())}return k};
h.Qj=function(c){c=a(c);d.log("M189",c);return h.Af(h.Zc(c))};h.Af=function(c,e){function k(c){for(var e=0;e<c.length;e++){var f=c[e];f!=b&&0>d.utils.wb(t,f)&&t.push(f)}}if(!c||0>=c.Ca.length)return null;e||(e=c);var b;if(0<e.Ca.length){if(b=e.Ca[0],0>d.utils.wb(c.Ca,b))return null}else return d.error("M190"),null;var a=e.serverSnapshotType||c.serverSnapshotType,g=e.hasEntryPointErrors||c.hasEntryPointErrors,t=[];k(c.Ca);k(e.Ca);var p={clientRequestGUID:b,btGlobalAccountName:c.btGlobalAccountName};
0<t.length&&(p.otherClientRequestGUIDs=t);0<h.zf(c.btTime,e.btTime).length&&(p.btTime=h.zf(c.btTime,e.btTime));null!==a&&(p.serverSnapshotType=a);null!==g&&(p.hasEntryPointErrors=g);return p};h.zf=function(d,e){for(var k=d.concat(e),h={},a={},g=0;g<k.length;g++){var t=k[g];t.id in h||(h[t.id]=-1);h[t.id]=Math.max(h[t.id],t.duration);t.id in a||(a[t.id]=-1);a[t.id]=Math.max(a[t.id],t.ert)}var k=[],p;for(p in h)b(h,p)&&k.push({id:p,duration:h[p],ert:a[p]});return k};h.Zc=function(c){if(!d.utils.isArray(c))return null;
for(var e=[],k=null,b=[],h=null,a=null,g=0;g<c.length;g++){var p=c[g];if("string"!==typeof p)return null;p=p.replace(/^"|"$/g,"");p=decodeURIComponent(p).split(",")[0].replace(/^\s+|\s+$/g,"").split(":");if(2===p.length){var r=p[1];switch(p[0]){case "clientRequestGUID":case "g":e.push(r);break;case "btId":case "i":b.push({id:r,duration:-1,ert:-1});break;case "btDuration":case "d":if(0===b.length)return null;p=d.utils.tg(r);if(!d.utils.ef(p)||-1>p)return null;b[b.length-1].duration=p;break;case "btERT":case "e":if(0===
b.length)return null;p=d.utils.tg(r);if(!d.utils.ef(p)||-1>p)return null;b[b.length-1].ert=p;break;case "serverSnapshotType":case "s":h=r;break;case "globalAccountName":case "n":k=r;break;case "hasEntryPointErrors":case "h":a=r}}}return 0===e.length?null:{Ca:e,btGlobalAccountName:k,btTime:b,serverSnapshotType:h,hasEntryPointErrors:a}};h.En=a})(d.correlation||(d.correlation={}))})(g||(g={}));(function(d){var h=d.conf||(d.conf={});h.Tm=3E3;h.useDebugBeaconParams=d.isDebug;h.gi=1E3;h.Ch=2;h.Bh=5;h.vh=
5;h.wh=20;h.Td=5E3;h.Oa=512;h.$g=10;h.Zg=64;h.Nh=10;h.Mh=10;h.Ih=300;h.Fh=2048;h.Pa=2048;h.Qa=760;h.rf={eumAppKey:"ky",userPageName:"un",clientRequestGUID:"cg",otherClientRequestGUIDs:"og",baseGUID:"bg",parentGUID:"mg",parentPageUrl:"mu",parentPageType:"mt",parentLifecyclePhase:"pp",pageType:"pt",pageUrl:"pu",pageReferrer:"pr",pageTitle:"pl",pageName:"pn",httpHeaders:"hh",parameter:"pa",navOrXhrMetrics:"mn",cookieMetrics:"mc",resourceTimingInfo:"rt",userData:"ud",userDataLong:"udl",userDataDouble:"udd",
userDataBoolean:"udb",userDataDate:"udt",errors:"er",ajaxError:"ae",xhrStatus:"xs",btTime:"bt",btGlobalAccountName:"btgan",serverSnapshotType:"ss",hasEntryPointErrors:"se",dataType:"dt",geoCountry:"gc",geoRegion:"gr",geoCity:"gt",localIP:"lp",ip:"ip",BEACONS:"B",ver:"vr",eom:"em",agentId:"ai",rootGUID:"rg",events:"es",guids:"gs",urlParts:"up",sequenceId:"si",eventType:"et",eventGUID:"eg",parentType:"at",serverMetadata:"sm",eventUrl:"eu",line:"ln",message:"dm",duration:"dn",id:"id",ert:"ert",parentUrl:"au",
parentPageName:"an",geo:"ge",metrics:"mx",timestamp:"ts",country:"c",region:"r",city:"t",method:"md",clientId:"ci"}})(g||(g={}));(function(d){d=d.beacons||(d.beacons={});d.numBeaconsSent=0;d.beaconsSent=[]})(g||(g={}));(function(d){(function(h){var a=function(){function b(){}b.prototype.send=function(k,e){var c=(e?d.conf.beaconUrlHttps:d.conf.beaconUrlHttp)+d.conf.corsEndpointPath+"/"+d.conf.appKey+"/adrum",b;d.utils.isFunction(d.xhrConstructor)&&d.utils.isFunction(d.xhrOpen)?(b=new d.xhrConstructor,
d.xhrOpen.call(b,"POST",c)):(b=new XMLHttpRequest,b.open("POST",c));b.setRequestHeader("Content-type","text/plain");var a=d.utils.za(k);null!=a&&(d.utils.isFunction(d.xhrConstructor)&&d.utils.isFunction(d.xhrSend)?d.xhrSend.call(b,a):b.send(a),d.log("M192",c),d.log("\n"),d.log("<hr/>"),d.isDebug&&h.beaconsSent.push(k),h.numBeaconsSent+=1)};return b}();h.Ug=a})(d.beacons||(d.beacons={}))})(g||(g={}));g||(g={});(function(d){var h=function(){function h(d,k,e){this.Fb=d;this.hk=k;this.qd=e}h.prototype.Ec=
function(){try{return h.Oe(this.hk.ADRUM)}catch(b){return d.error("M193"),h.Oe(d)}};h.Oe=function(d){return d.correlation.getPageGUID()};return h}();d.Qg=h})(g||(g={}));(function(d){d.beacons||(d.beacons={})})(g||(g={}));(function(d){(function(d){var a=function(){function b(){this.yb=[];this.xc={}}b.prototype.Bb=function(k){if(!k)return"";if(d.hasOwnPropertyDefined(this.xc,k))return this.xc[k];var e=this.yb.length;this.xc[k]=e;this.yb[e]=k;return e};return b}();d.Sd=a})(d.utils||(d.utils={}))})(g||
(g={}));(function(d){(function(h){var a=d.utils.map,b=function(){function d(){}d.bm=function(d){d=(d||"").match(/([^:\/?#]+:\/\/)?([^?#]+)?(\?[^#]*)?(#[\s\S]*)?/);var c={};d[1]&&(c.protocol=d[1].substring(0,d[1].length-3));d[2]&&(c.path=d[2]);d[3]&&(c.Bl=d[3]);d[4]&&(c.anchor=d[4]);return c};d.fj=function(e,c){var b=d.bm(e),h="";b.protocol&&(h+=c.Bb(b.protocol),h+="://");b.path&&(h+=a(b.path.split("/"),c.Bb,c).join("/"));return h+=a([b.Bl,b.anchor],function(d){return d?d[0]+c.Bb(d.slice(1)):""},c).join("")};
d.dj=function(d,c){return""+c.Bb(d)};return d}();h.Ed=b})(d.beacons||(d.beacons={}))})(g||(g={}));(function(d){(function(h){(function(h){function b(){var c=null,k=null;try{c=localStorage[e]}catch(b){}if(c)try{c=k=JSON.parse(c),d.utils.isObject(c)&&d.utils.isNumber(c[l])&&-1<c[l]?g=k:d.error("M194")}catch(h){d.exception(h,"M195");try{delete localStorage[e]}catch(f){d.exception(f,"M196")}}}function k(){try{var k=d.channel,b=g[c]||g[f],h=k&&k.U&&k.U.R&&k.U.R.id||(d.utils.isString(b)?b:d.utils.generateGUID());
g[c]=g[f]=h;localStorage[e]=d.utils.za(g)}catch(a){}}var e="ADRUM_CLIENTINFO",c="agentId",f="clientId",l="seqId",g;b();g||(g={seqId:0});k();h.Aj=function(){b();var d=g[l]++;k();return d}})(h.se||(h.se={}))})(d.gg||(d.gg={}))})(g||(g={}));(function(d){(function(h){var a=function(){function b(){this.urlCapture={filterURLQuery:!1};this.Sf=/;jsessionid=[^/?]+/;h.mergeJSON(this.urlCapture,d.conf.userConf.urlCapture);h.isBoolean(this.urlCapture.filterURLQuery)||h.isArray(this.urlCapture.filterURLQuery)||
(d.log("M197"),this.urlCapture.filterURLQuery=!1)}b.$l=function(d){for(var e=0,c=0;c<d.length;c++)e=(e<<5)-e+d.charCodeAt(c),e|=0;return e};b.prototype.Kj=function(d){var e="",c,b;if(!h.isString(d))return"";c=d.indexOf("?")+1;0<c&&(b=d.indexOf("#"),0>b?e=d.substring(c):c<=b&&(e=d.substring(c,b)));return e};b.prototype.kj=function(d){var e="",c=this.urlCapture.filterURLQuery,b={},a=0,g,n,q;if(!h.isString(d)||""===d)return"";if(!1===c)return d;g=this.Kj(d);if(""===g)return d;if(h.isArray(c)){for(q=
0;q<c.length;q++)b[c[q]]=!0;c=g+"&";for(q=0;q<c.length;q++)switch(c[q]){case "=":n=c.substring(a,q);break;case "&":case ";":n=n||c.substring(a,q),q++,b[n]||(e+=c.substring(a,q)),a=q,n=null}e=e.substring(0,e.length-1)}""==e&&(g="?"+g);return d.replace(g,e)};b.prototype.ma=function(d){if(null===d||void 0===d)return null;if(""===d)return"";var e=d.match(this.Sf),c=d;if(null!=e){var b=d.indexOf("?");if(0>b||b>e.index)c=d.replace(this.Sf,"")}return c=this.kj(c)};b.prototype.Ce=function(d){if(null===d||
void 0===d)return null;var e=d.indexOf("?"),c=d.indexOf("#");0>e&&(e=Number.MAX_VALUE);0>c&&(c=Number.MAX_VALUE);return d.substring(0,Math.min(e,c))};b.prototype.gl=function(d){if(null===d||void 0===d)return null;var e=this.Ce(d);return e+"?"+b.$l(d.substring(e.length))};return b}();h.Xm=a;h.V=new a})(d.utils||(d.utils={}))})(g||(g={}));(function(d){(function(h){(function(h){var b=function(){function b(e,c,k){var h=this;this.Gl=0;this.cd=[];this.Ve=!1;this.Xj=k;d.utils.addEventListener(window,"message",
function(d){h.kl(d)});this.Wj=d.utils.Si(c,e)}b.prototype.kl=function(e){var c;try{if(c=JSON.parse(e.data),"ADRUM_XD"!==c.name)d.log("M198");else if(!0===c.success)if(-1===c.id&&"iframe-ready"===c.data)this.Ve=!0,this.Xj();else{if(this.cd[c.id])this.cd[c.id](c.data)}else d.error("M199",e.data)}catch(b){d.log("M200",b)}};b.prototype.send=function(e,c,b,k){if(this.Ve){var h=this.Gl++;this.cd[h]=k;this.Wj.contentWindow.postMessage(d.utils.za({id:h,action:e,key:c,value:b}),"*")}};b.prototype.generateGUID=
function(d,c){this.send("generateGUID",d,null,c)};return b}();h.Wg=b})(h.sg||(h.sg={}))})(d.Ig||(d.Ig={}))})(g||(g={}));(function(d){(function(h){var a=function(){function e(){this.ke=new b(e.Mg);this.Hg=new b(e.Og);this.Jm=new k(e.Ng)}e.prototype.init=function(c){this.channel=c;d.utils.gm()&&d.utils.fm()?d.utils.hm()&&e.Pk()?this.rm():this.Bg():e.Bf=!0};e.prototype.Bg=function(){var c=this.ke.load();e.Nk(c)||(c={ver:d.conf.agentVer,id:d.utils.generateGUID()},this.ke.save(c));e.R=c};e.prototype.rm=
function(){var c=this,b=this.Hg.load();e.Ok(b)?e.R=b:(d.log("M201"),this.Jm.load(function(b){e.jf(b)?(b={ver:d.conf.agentVer,id:b,ttl:(new Date).getTime()+e.ah},c.Hg.save(b),e.R=b,d.log("M202")):d.log("M203")}),d.utils.tryPeriodically(e.mc,function(){return c.isReady()},function(){return c.onReady()},function(){return c.Vc()}))};e.Pk=function(){return d.conf.userConf&&d.conf.userConf.xd&&d.conf.userConf.xd.enable};e.Nk=function(d){return d&&d.id&&0<d.id.length};e.Ok=function(d){return d&&e.jf(d.id)&&
d.ttl>(new Date).getTime()};e.jf=function(c){return d.utils.isString(c)&&0<c.length&&0===c.indexOf("XD_")};e.prototype.isReady=function(){return e.Bf||d.utils.isDefined(e.R)};e.prototype.onReady=function(){this.channel.onResolverReady()};e.prototype.Vc=function(){d.log("M204");this.Bg();this.channel.onResolverReady()};e.mc=function(d){return 10<d?-1:[1,50,100,500][d-1]||1E3};return e}();a.Mg="ADRUM_AGENT_INFO";a.Og="ADRUM_XD_AGENT_INFO";a.Ng="ADRUM_XD_AGENT_ID";a.ah=6048E5;a.Bf=!1;h.U=a;var b=function(){function e(d){this.je=
d}e.prototype.load=function(){var c=null;try{var e=localStorage.getItem(this.je);e&&(c=JSON.parse(e))}catch(b){d.exception(b,"M205")}return c};e.prototype.save=function(c){try{var e=d.utils.za(c);e&&localStorage.setItem(this.je,e)}catch(b){d.exception(b,"M206")}};return e}(),k=function(){function e(d){this.ui=d}e.prototype.load=function(c){var e=this;try{var b=new d.Ig.sg.Wg("cross-domain-store-server-iframe",d.conf.adrumXdUrl,function(){b.generateGUID(e.ui,c)})}catch(k){d.exception(k,"M207")}};return e}()})(d.channel||
(d.channel={}))})(g||(g={}));(function(d){(function(h){var a=d.utils.isString,b=d.utils.isNumber,k=function(){function e(){}e.prototype.Kb=function(c,b,k){c={ver:d.conf.agentVer,dataType:"R",rootGUID:k.Ec(),events:c};d.channel.U.R&&d.channel.U.R.id&&(c.agentId=d.channel.U.R.id);b&&(c.geo=b);return e.tl(c)};e.tl=function(c){d.isDebug||(c=e.Li(c));return c};e.Li=function(c){var k=new d.utils.Sd,g=new d.utils.Sd;c=d.utils.Gc(null,c,e.Fc,function(c,n){if(!a(n))return n;if(e.Mk(c)){var q=e.Ek(c)&&b(d.conf.userConf.maxUrlLength)?
d.conf.userConf.maxUrlLength:d.conf.Oa;n=e.nd(n,q);n=h.Ed.fj(n,k)}else n=e.Dk(c)?e.nd(n,d.conf.Qa):e.nd(n,d.conf.Fh);e.wk(c)&&(n=h.Ed.dj(n,g));return n},e.Zk);c[e.Fc("guids")]=g.yb;c[e.Fc("urlParts")]=k.yb;return c};e.Mk=function(d){return"eventUrl"==d||"parentUrl"==d||"pageReferrer"==d||"pageUrl"==d||"u"==d};e.wk=function(d){return"eventGUID"==d||"parentGUID"==d||"rootGUID"==d||"clientRequestGUID"==d};e.Dk=function(d){return"userPageName"==d};e.nd=function(d,e){return d.length>e?d.substr(0,e-3)+
"...":d};e.Ek=function(d){return"eventUrl"==d||"parentUrl"==d||"pageReferrer"==d};e.Fc=function(c){if(d.conf.useDebugBeaconParams)return c;var e=d.conf.rf[c];return"undefined"===typeof e?c:e};e.Zk=function(d){d=""+d;return 0===d.indexOf("userData")||"parameter"===d};return e}();h.Tg=k})(d.beacons||(d.beacons={}))})(g||(g={}));(function(d){(function(h){var a=function(){function b(){}b.prototype.send=function(d,e){for(var c=0;c<d.length;c++)this.Rl(d[c],e)};b.prototype.Rl=function(b,e){var c=(e?d.conf.beaconUrlHttps:
d.conf.beaconUrlHttp)+d.conf.imageEndpointPath,a=document.createElement("img");a.T=!0;try{a.src=c+b}catch(g){}d.isDebug&&h.beaconsSent.push(b);h.numBeaconsSent+=1};return b}();h.rh=a})(d.beacons||(d.beacons={}))})(g||(g={}));(function(d){(function(d){d.kb=function(d,b){if(3>=b)return"...";d.length>b&&(d=d.substring(0,b-3)+"...");return d};d.xg=function(d,b){if(3>=b)return"...";d.length>b&&(d=d.substring(0,(b-3)/2)+"..."+d.substring(d.length-(b-3)/2,d.length));return d};d.nm=function(a,b){a.length<=
b||(a=d.kb(a,b-1),a+=":");return a};d.lm=function(a,b,k,e,c,f){a=d.nm(a,e);k=d.kb(k,c);a.length+b.length+k.length>f-3&&(b=d.kb(b,f-3-a.length-k.length));return 0<k.length?a+"//"+b+":"+k:a+"//"+b};d.mm=function(a,b,k){a=d.map(a,function(c){return d.xg(c,b)});if(a.length>k){var e=a[0];a=a.slice(a.length-k);a.unshift("...");""==e&&a.unshift(e)}return a};d.om=function(a,b,k,e,c){e=d.lm(a.protocol,a.hostname,a.port,e,c,b);k--;c=d.kb(a.search,b);k--;var f=d.kb(a.hash,b);k--;a=a.pathname.split("/");var g=
"";0<a.length&&(g=a.pop(),g=d.xg(g,b),k--);a=d.mm(a,b,k);return 0==a.length?e+g+c+f:e+a.join("/")+"/"+g+c+f}})(d.utils||(d.utils={}))})(g||(g={}));(function(d){(function(d){var a=function(){function d(){}d.Lc=function(){for(var k=0;k<d.Ld.length;k++)d.ia[d.Ld[k]]=d.$.lh;for(k=0;k<d.Id.length;k++)d.ia[d.Id[k]]=d.$.fh;d.ia.js=d.$.ai;d.ia.css=d.$.CSS;d.ia.svg=d.$.ci;d.ia.html=d.$.Kd;d.ia.htm=d.$.Kd};d.Cc=function(d){return d.duration?d.duration:d.responseEnd&&d.startTime?d.responseEnd-d.startTime:-1};
d.Re=function(k){var e;return(k=k.pathname)&&-1!=(e=k.lastIndexOf("."))?d.ia[k.substring(e+1,k.length).toLowerCase()]||d.$.OTHER:d.$.OTHER};return d}();a.$={lh:"img",ai:"script",CSS:"css",ci:"svg",Kd:"html",fh:"font",OTHER:"other"};a.Ld="bmp gif jpeg jpg png webp".split(" ");a.Id=["ttf","woff","otf","eot"];a.ia={};d.Ra=a;a.Lc()})(d.events||(d.events={}))})(g||(g={}));(function(d){(function(d){var a=function(){function d(k){function e(d){c.marks.push(0==k[d]?-1:Math.round(k[d]-c.Ff))}this.marks=[];
var c=this;this.Ff=k.startTime;this.tk(k)?(this.Fe=d.Fd,e("startTime"),e("fetchStart")):(this.Fe=d.Zd,e("startTime"),e("redirectStart"),e("redirectEnd"),e("fetchStart"),e("domainLookupStart"),e("domainLookupEnd"),e("connectStart"),e("secureConnectionStart"),e("connectEnd"),e("requestStart"),e("responseStart"));e("responseEnd")}d.Cj=function(){var k={};k[d.Zd]=d.$h;k[d.Fd]=d.Vg;return k};d.prototype.tk=function(d){return this.va(d.redirectStart)&&this.va(d.redirectEnd)&&(this.va(d.domainLookupStart)||
this.va(d.domainLookupEnd)||this.va(d.connectStart)||this.va(d.connectEnd))&&this.va(d.secureConnectionStart)};d.prototype.va=function(d){return!d||0===d};return d}();a.Zd=1;a.Fd=2;a.$h="startTime redirectStart redirectEnd fetchStart dnsLookupStart dnsLookupEnd connectStart secureConnectionStart connectEnd requestStart responseStart responseEnd".split(" ");a.Vg=["startTime","fetchStart","responseEnd"];d.Yd=a})(d.events||(d.events={}))})(g||(g={}));(function(d){(function(d){var a=function(){function d(){}
d.prototype.Sb=function(d,e){if(d)return d.slice(0,e)};return d}();d.gh=a})(d.events||(d.events={}))})(g||(g={}));(function(d){(function(d){var a=function(){function b(){}b.prototype.Sb=function(b,e){if(b){if(b.length<=e)return b;for(var c=[],a=0;a<b.length;a++)c.push({dd:b[a],index:a});c.sort(function(c,e){return-(d.Ra.Cc(c.dd)-d.Ra.Cc(e.dd))});c=c.slice(0,e);c.sort(function(d,c){return d.index-c.index});for(var g=[],a=0;a<c.length;a++)g.push(c[a].dd);return g}};return b}();d.ae=a})(d.events||(d.events=
{}))})(g||(g={}));(function(d){(function(d){var a=function(){function b(){}b.prototype.Sb=function(b,e){if(b){if(b.length<=e)return b;for(var c=1,a=Math.floor(Number.MAX_VALUE/4),g=b.length;c<a;){for(var m=b.length-1;0<=m;m--)if(d.Ra.Cc(b[m])<c&&(b.splice(m,1),g--),g<=e)return b;c*=4}return(new d.ae).Sb(b,e)}};return b}();d.Zh=a})(d.events||(d.events={}))})(g||(g={}));(function(d){(function(h){var a=d.utils.hasOwnPropertyDefined,b=function(){function e(c,b,a){this.version=2;this.resourceTimingInfo=
{};this.Ye={};this.Ze={};this.Xf={};this.Yf={};this.ed=[];this.oi=function(c,e,b){if(c&&e&&0<e.length){this.jm=c;for(var a=new k,f=new k,g=0;g<e.length;g++){var l=e[g],m=d.utils.parseURI(d.utils.V.ma(l.name)),v=l.initiatorType,B=h.Ra.Re(m),C=new h.Yd(l);this.ed.push({u:this.pm(m),i:a.Ne(this.Ze,v),r:f.Ne(this.Yf,B),f:C.Fe,o:this.vj(0===g&&l.isBase,C.Ff,c,b),m:C.marks,e:d.utils.isDefined(l.encodedBodySize)?l.encodedBodySize:-1,d:d.utils.isDefined(l.decodedBodySize)?l.decodedBodySize:-1,s:d.utils.isDefined(l.transferSize)?
l.transferSize:-1,p:d.utils.isDefined(l.nextHopProtocol)?l.nextHopProtocol:""})}}};var g=e.wj();this.Ii(g,c);c=this.Nl(g,c);this.oi(b||d.monitor.navMonitor.navTiming&&d.monitor.navMonitor.navTiming.navigationStart,c,a);this.clearResourceTimings()}e.Lc=function(){var c=d.conf.userConf&&d.conf.userConf.resTiming&&d.conf.userConf.resTiming.sampler;e.Ml=c&&"FirstN"==c?new h.gh:c&&"TopN"==c?new h.ae:new h.Zh};e.prototype.We=function(d,e){d[e]=d[e]?d[e]+1:1};e.prototype.pm=function(e){return d.utils.om(e,
"number"===typeof d.conf.userConf.maxResUrlSegmentLength?d.conf.userConf.maxResUrlSegmentLength:d.conf.Zg,"number"===typeof d.conf.userConf.maxResUrlSegmentNumber?d.conf.userConf.maxResUrlSegmentNumber:d.conf.$g,d.conf.Nh,d.conf.Mh)};e.prototype.Ii=function(d,e){d&&this.Xe(d);if(e&&0<e.length)for(var b=0;b<e.length;b++)this.Xe(e[b])};e.prototype.Xe=function(e){var b=d.utils.parseURI(d.utils.V.ma(e.name)),b=h.Ra.Re(b);this.We(this.Ye,e.initiatorType);this.We(this.Xf,b)};e.prototype.Nl=function(c,b){if(b&&
0<b.length){var k=d.conf.userConf&&d.conf.userConf.resTiming&&d.conf.userConf.resTiming.maxNum||d.conf.Ih;c&&k--;b=e.Ml.Sb(b,k);c&&b.unshift(c)}return b};e.prototype.vj=function(e,b,k,h){return e?1:d.utils.isDefined(h)?Math.round(b+k-h):Math.round(b)};e.prototype.build=function(){return 0==this.ed.length?null:{v:this.version,ic:this.Ye,it:this.Ze,rc:this.Xf,rt:this.Yf,f:h.Yd.Cj(),t:this.jm,r:this.ed}};e.wj=function(){var e=d.monitor.navMonitor.navTiming,b=null;if(e){var b={},k;for(k in e)a(e,k)&&
(b[k]=e[k]);b.initiatorType="other";b.name=document.URL;b.navigationStart&&!b.startTime&&(b.startTime=b.navigationStart);b.isBase=!0}return b};e.prototype.clearResourceTimings=function(){d.conf.userConf&&d.conf.userConf.resTiming&&d.conf.userConf.resTiming.clearResTimingOnBeaconSend&&d.monitor.navMonitor.clearResourceTimings()};return e}();h.ResourceTimingInfoBuilder=b;var k=function(){function d(){this.al=1}d.prototype.Ne=function(d,e){d[e]||(d[e]=this.al++);return d[e]};return d}();b.Lc()})(d.events||
(d.events={}))})(g||(g={}));(function(d){d.events||(d.events={})})(g||(g={}));(function(d){(function(h){var a=function(){function b(){}b.prototype.D=function(b,e){void 0===e&&(e={});var c={eventGUID:b.guid(),eventType:b.type(),eventUrl:d.utils.V.ma(b.url()||document.URL),timestamp:d.utils.now()};b.type()!==d.EventType.PageView&&d.utils.mergeJSON(c,{parentGUID:b.parentGUID()||d.correlation.getPageGUID(),parentUrl:d.utils.V.ma(b.parentUrl()||document.URL),parentType:b.parentType()||(d.utils.compareWindows(top,
window)?d.EventType.PageView:d.EventType.IFRAME)});var a=d.EventType[b.type()],a=h.aa.Tj(a,d.conf.userConf,e,d.conf.Pa),g;for(g in a)c[g]=a[g];return c};return b}();h.Ma=a})(d.events||(d.events={}))})(g||(g={}));(function(d){(function(h){var a=d.utils.isNumber,b=d.utils.isString,k=d.utils.isObject,e=d.utils.ve,c=d.utils.Oc,f=d.utils.isBoolean,g=function(){function c(){}c.Uc=function(e,c){var b=!1;if(k(e)){var h=d.utils.za(e);if(!h||h.length<=c)b=!0}return b};c.ld=function(d,e,k){if(b(e))if(e.length>
k)c.Ia(d,k,e.length);else return e;else c.Qc(d,"string")};c.Mb=function(d,e){return function(b,h,a){if(k(h)){var g,f;for(f in h)d(h[f])?(g=g||{},g[f]=h[f]):c.Qc(b,e,f);if(g){if(c.Uc(g,a))return g;c.Ia(b,a)}}else c.Qc(b,"object")}};c.Qc=function(d,c,b){e(d+" dropped because it was not a "+c+(b?", field name "+b:""))};c.Ia=function(d,c,b){e("User event info field "+d+" dropped because it is too long"+(b?" ("+b+" exceeds "+c+")":""))};return c}();g.Tj=function(e,c,b,h){if(c=c&&c.userEventInfo&&c.userEventInfo[e]){try{var a=
d.utils.isFunction(c)?c.call(null,b):c}catch(f){d.exception(f,"M209",e)}if(k(a))return g.ym(a,h)}};g.ym=function(d,e){var c={},b;for(b in g.De)if(b in d){var k=g.De[b](b,d[b],e);k&&(c[b]=k)}return c};g.jl=g.Mb(b,"string");g.il=g.Mb(c,"integer");g.Cf=g.Mb(a,"number");g.hl=g.Mb(f,"boolean");g.De={userPageName:g.ld,userData:g.jl,userDataLong:g.il,userDataDouble:g.Cf,userDataBoolean:g.hl,userDataDate:g.Cf};h.aa=g})(d.events||(d.events={}))})(g||(g={}));(function(d){(function(h){var a=d.utils.isDefined,
b=function(b){function e(){return null!==b&&b.apply(this,arguments)||this}u(e,b);e.setPageName=function(d){e.na=d};e.addUserData=function(d,b){e.lb=e.lb||{};e.lb[d]=b};e.prototype.D=function(c){c=b.prototype.D.call(this,c||new h.PageView);var g=this.Ej(),l=this.xj();d.conf.viz&&(g&&d.utils.wc(document.getElementById(d.conf.viz),g,"navtime"),d.utils.wc(document.getElementById(d.conf.viz),l,"cookie"));l.PLC=1;g&&(g.PLC=1);d.monitor.ErrorMonitor.hadErrors&&(l.EPM=1,g&&(g.EPM=1));d.utils.mergeJSON(c,
{eventGUID:d.correlation.getPageGUID(),eventType:d.utils.compareWindows(top,window)?d.EventType.PageView:d.EventType.IFRAME,cookieMetrics:l});var m=-1;g&&g.timestamp?m=g.timestamp:l&&l.timestamp&&(m=l.timestamp);0<m&&d.utils.mergeJSON(c,{timestamp:m});g&&(c.metrics=g);document.referrer&&null!==document.referrer&&0<document.referrer.length&&(c.pageReferrer=d.utils.V.ma(document.referrer));g=e.Hj();0<g.length&&(c.pageTitle=g);g=d.correlation.Te();null!==g&&(c.serverMetadata=g);g=d.conf.spa2?0<d.monitor.resourceMonitor.basePageResourceBuffer.length?
(new h.ResourceTimingInfoBuilder(d.monitor.resourceMonitor.basePageResourceBuffer)).build():null:d.monitor.resourceMonitor.resTiming?(new h.ResourceTimingInfoBuilder(d.monitor.resourceMonitor.resTiming)).build():null;null!==g&&(c.resourceTimingInfo=g);!a(c.userData)&&a(e.lb)&&(h.aa.Uc(e.lb,d.conf.Pa)?c.userData=e.lb:h.aa.Ia("userData",d.conf.Pa));!a(c.userPageName)&&a(e.na)&&(h.aa.ld("userPageName",e.na,d.conf.Qa)?c.userPageName=e.na:h.aa.Ia("userPageName",d.conf.Qa));e.userPageName=c.userPageName;
return c};e.prototype.Ej=function(){if(!d.monitor.navMonitor.navTiming)return null;var c={},b=e.Pe(d.monitor.navMonitor.navTiming,c,"NT"),k=h.metricSpec[d.EventType.PageView],a;for(a in k){var g=k[a];b.add(g.name,g.start,g.end)}c.timestamp=d.monitor.navMonitor.navTiming.navigationStart;return c};e.prototype.xj=function(){var c={};d.commands.marks&&(e.Pe(d.commands.marks,c,"CK").add("PLT","starttime","onload").add("FBT","starttime","firstbyte").add("FET","firstbyte","onload").add("DRT","firstbyte",
"onready").add("PRT","onready","onload").add("DOM","starttime","onready"),c.timestamp=d.commands.marks.starttime?d.commands.marks.starttime:d.commands.marks.firstbyte);return c};e.Hj=function(){var e=d.conf.userConf,e=e&&e.page,b;b=e&&"captureTitle"in e?e.captureTitle:!0;var k,h;e&&(k="title"in e,h=e.title);k=b?k?d.utils.isFunction(h)?h():h:document.title:"";if(d.utils.isString(k))return k;d.utils.ve("Ignoring wrong type of page title: "+typeof k);return""};e.mi=function(e,b,k,h,a,g){b=h[b];k=h[k];
b&&k?a[e]=k-b:d.log("M210",g,e,b,k)};e.Pe=function(d,b,k){var h={add:function(a,g,t){e.mi(a,g,t,d,b,k);return h}};return h};return e}(h.Ma);h.ja=b})(d.events||(d.events={}))})(g||(g={}));(function(d){(function(h){(function(h){function b(c,h){var a,m=h[c],q=typeof m;r.push(c);var C=p[r.join(".")];if(d.utils.isFunction(C))a=C(m);else switch(q){case "string":a="number"==typeof C?n(m,e,C):e(m);break;case "number":a=l(m);break;case "object":if(m)if(d.utils.isArray(m))a=g(m,!1,!1);else{a=[];for(var z in m)t(m,
z)&&(q=b(z,m))&&(k(c)&&"timestamp"==z||a.push({Ib:z,v:q}));if(k(c)){for(m=0;m<a.length;m++)a[m]=a[m].Ib+e(":")+a[m].v;a=e("{")+a.join(e(","))+e("}")}else{for(m=0;m<a.length;m++)z=a[m],q=z.Ib,d.conf.useDebugBeaconParams||((C=d.conf.rf[z.Ib])?q=C:d.error("M211",z.Ib)),a[m]=q+"="+z.v;a=a.join("&")}}else a=null}r.pop();return a}function k(d){return"navOrXhrMetrics"==d||"cookieMetrics"==d}function e(d){return"undefined"===typeof d||null===d||0===d.length?null:encodeURIComponent(d)}function c(d){return encodeURIComponent(encodeURIComponent(d))}
function g(d,c,h){void 0===c&&(c=!1);void 0===h&&(h=!0);if(0===d.length)return null;var k=[];if(c)k=d;else for(c=0;c<d.length;c++)k.push(b(c,d));return e("[")+k.join(e(","))+e(h?">":"]")}function l(d){d=Math.round(d);d<h.Xd&&(d=h.Xd);d>h.Ud&&(d=h.Ud);return e(d)}function m(d,b){if(d>b||0>d)d=h.Sh;return e(d)}function n(e,b,c,h){void 0===h&&(h=!0);if("undefined"===typeof e||null===e||0===e.length)return null;var k=3<=c?"...":"";d.assert(c>=k.length);for(var a=!1,g=null;;){try{g=b(e);if(null===g)return null;
if(g.length<=c)break}catch(f){}var l;a?l=e.length-1:(a=!0,l=c-=k.length);var m=h?0:Math.max(e.length-l,0);e=e.substr(m,l)}a&&(g=h?g+k:k+g);return g}function q(e,b,c){if(0==c)return h.dc;if(b<e)return 0;b=h.dc+(b-e)/c;d.assert(b>=h.dc);d.log("M212",e,b);return b}var t=d.utils.hasOwnPropertyDefined;h.Sh=-1;h.Oa=180;h.Kh=50;h.Lh=50;h.Eh=40;h.dc=50;h.sh=50;h.Wd=128;h.zh=30;h.Ah=30;h.yh=30;h.Gh=8;h.Xd=-99999;h.Ud=999999;h.th=2E3;h.Jh=2;h.uh=99999999;var p={".pageUrl":h.Oa,".parentPageUrl":h.Oa,".pageReferrer":h.Oa,
".pageTitle":h.Kh,".userPageName":h.Lh,".geoCountry":h.zh,".geoRegion":h.Ah,".geoCity":h.yh,".localIP":h.Gh,".otherClientRequestGUIDs":function(d){d=d||[];var e=d.slice(0,h.Jh);return g(e,!1,e.length<d.length)},".btTime":function(e){e=e||[];for(var b=e.slice(0,d.conf.vh),c=[],k=0;k<b.length;k++){var n=b[k];c.push(g([m(Number(n[0]),h.uh),l(n[1]),l(n[2])],!0,!1))}return g(c,!0,b.length<e.length)},".ajaxError":function(d){return g([c(d[0]),n(d[1],c,h.sh)],!0,!1)},".userData":function(d){d=d||[];for(var e=
!1,b=0,k=[],l=0;l<d.length;l++){var m=d[l];k[l]=g([c(m[0]),c(m[1])],!0,!1);b+=k[l].length;if(b>h.Wd){e=!0;break}}for(;;){d=g(k,!0,e);if(null===d||d.length<=h.Wd)return d;k.pop();e=!0}}},r=[];h.cj=function(e,k){void 0===k&&(k=!0);r=[];var m=[];e.errors&&(m=e.errors,e.errors=null);var p=b("",{"":e});if(m&&0<m.length){for(var t=q(k?870:354,h.th-p.length,m.length),C=[],z=0;z<m.length;z++){var u=m[z],A=d.utils.V.Ce(d.utils.V.ma(u[0]));C.push(g([n(A,c,h.Eh,!1),d.utils.Oc(u[1])?l(u[1]):-1,n(u[2],c,t)],!0,
!1))}m=g(C,!0,!1);p+="&errors="+m}return p};h.on=b;h.On=e;h.element=c;h.gn=g;h.jn=l;h.Dn=m;h.truncate=n;h.Kn=q})(h.Rd||(h.Rd={}))})(d.beacons||(d.beacons={}))})(g||(g={}));(function(d){(function(h){var a=d.utils.hasOwnPropertyDefined,b=d.utils.wb,k=function(){function e(){}e.prototype.Kb=function(b,k,a){for(var g=[],n=[],q=null,t=[],p=0;p<b.length;p++){var r=b[p];if(r.eventType===d.EventType.Error){var u=r;n.push([r.eventUrl+"",d.utils.Oc(u.line)?u.line:void 0,u.message+""])}else{if(r.eventType===
d.EventType.PageView||r.eventType===d.EventType.IFRAME)q=r;t.push(r)}}b=t;if(0<n.length)for(q&&(q.errors=n.splice(0,d.conf.Ch));0<n.length;)r=n.splice(0,d.conf.Bh),q=e.ml.D(),q.errors=r,q.isErrorEvent=!0,q.cookieMetrics=null,q.metrics=null,q.resourceTimingInfo=null,b.push(q);for(n=0;n<b.length;n++)r=b[n],d.log("M213"),r.resourceTimingInfo=null,e.pj(r,k,a),q=e.transform(r),g.push(h.Rd.cj(q,r.isErrorEvent));return g};e.pj=function(e,b,h){e.ver=this.mh;e.rootGUID=h.Ec();e.geo=b;e.dataType="R";e.eom=
1;e.eumAppKey=d.conf.appKey;e.PLC=1};e.transform=function(d){var b={};e.Eg("",{"":d},b);return b};e.Eg=function(c,h,k){h=h[c];var g=e.of[c];if("metrics"===c||"cookieMetrics"===c)k[g]=h;else if("btTime"===c&&d.utils.isArray(h)&&0<h.length){c=[];for(var n=0;n<h.length;n++)c.push([h[n].id,h[n].duration,h[n].ert]);k[g]=c}else if("userData"===c&&d.utils.isObject(h))k[g]=d.utils.Wk(h);else if(!(c&&-1<b(["userDataLong","userDataDouble","userDataBoolean","userDataDate"],c)))if(d.utils.isObject(h))for(n in h)a(h,
n)&&e.Eg(n,h,k);else e.of[c]&&("eventType"===c&&h>d.EventType.Ajax&&(h=d.utils.compareWindows(top,window)?d.EventType.PageView:d.EventType.IFRAME),k[g]=h)};return e}();k.ml=new d.events.ja;k.mh=3;k.of={eumAppKey:"eumAppKey",userPageName:"userPageName",rootGUID:"baseGUID",parentGUID:"parentGUID",parentUrl:"parentPageUrl",parentType:"parentPageType",parentLifecyclePhase:"parentLifecyclePhase",eventType:"pageType",eventUrl:"pageUrl",pageReferrer:"pageReferrer",pageTitle:"pageTitle",metrics:"navOrXhrMetrics",
xhrMetrics:"navOrXhrMetrics",resourceTimingInfo:"resourceTimingInfo",cookieMetrics:"cookieMetrics",userData:"userData",errors:"errors",ajaxError:"ajaxError",dataType:"dataType",country:"geoCountry",region:"geoRegion",city:"geoCity",localIP:"localIP",ver:"ver",eom:"eom",eventGUID:"clientRequestGUID",otherClientRequestGUIDs:"otherClientRequestGUIDs",btTime:"btTime",serverSnapshotType:"serverSnapshotType",hasEntryPointErrors:"hasEntryPointErrors"};h.qh=k})(d.beacons||(d.beacons={}))})(g||(g={}));(function(d){(function(d){var a=
function(){function d(){}d.prototype.send=function(){};return d}();d.eh=a})(d.beacons||(d.beacons={}))})(g||(g={}));(function(d){(function(d){var a=function(){function d(){}d.prototype.Kb=function(){return null};return d}();d.dh=a})(d.beacons||(d.beacons={}))})(g||(g={}));(function(d){(function(h){var a=function(){function b(d){this.Rk=d}b.prototype.send=function(b){try{this.Rk.postMessage(d.utils.za(b)),d.log("M214"),h.numBeaconsSent+=1}catch(e){d.log("M215")}};return b}();h.jh=a})(d.beacons||(d.beacons=
{}))})(g||(g={}));(function(d){(function(h){var a=function(){function b(){}b.prototype.Kb=function(b,e,c){b={ver:d.conf.agentVer,dataType:"R",rootGUID:c.Ec(),events:b};d.channel.U.R&&d.channel.U.R.id&&(b.agentId=d.channel.U.R.id);e&&(b.geo=e);return b};return b}();h.ih=a})(d.beacons||(d.beacons={}))})(g||(g={}));(function(d){var h=function(){function h(){}h.ue=function(b,h){if(!b)return null;var e=b.ADRUM.lifecycle;if(!e||!e.getPhaseCallbackTime)return null;var c=h.getPhaseCallbackTime("AT_ONLOAD"),
e=e.getPhaseCallbackTime("AT_ONLOAD"),a=null==e;return null==c?(d.error("M216"),null):d.lifecycle.getPhaseID(a||c<=e?"AFTER_FIRST_BYTE":"AFTER_ONLOAD")};return h}();d.Wh=h;d.cPLPI=h.ue})(g||(g={}));(function(d){(function(h){var a=function(){function b(b){this.ready=!1;this.geoResolverUrl=b;d.utils.isString(b)&&0<d.utils.trim(b).length&&(this.geoResolverUrl=b+"/resolve.js")}b.prototype.init=function(b){this.channel=b;if(this.sc()&&(d.geo=this.pd(),this.vi()||this.Ob()&&!this.He())){this.channel.fd(d.geo.result);
return}this.He()?(this.Ob()&&(this.geoResolverUrl+="?ip="+encodeURIComponent(d.conf.userConf.geo.localIP)),this.vm()):(this.ready=!0,this.channel.onResolverReady())};b.prototype.sc=function(){return d.utils.isDefined(d.conf.userConf)&&d.utils.isDefined(d.conf.userConf.geo)};b.prototype.Ob=function(){return this.sc()&&d.utils.isDefined(d.conf.userConf.geo.localIP)&&!d.utils.isDefined(d.conf.userConf.geo.city)&&!d.utils.isDefined(d.conf.userConf.geo.region)&&!d.utils.isDefined(d.conf.userConf.geo.country)};
b.prototype.pd=function(){return{failed:!1,result:{country:d.conf.userConf.geo.country,region:d.conf.userConf.geo.region,city:d.conf.userConf.geo.city,localIP:this.ej(d.conf.userConf.geo.localIP)}}};b.prototype.vi=function(){return this.sc()&&d.utils.isDefined(d.conf.userConf.geo.localIP)&&d.utils.isDefined(d.conf.userConf.geo.city)&&d.utils.isDefined(d.conf.userConf.geo.region)&&d.utils.isDefined(d.conf.userConf.geo.country)};b.prototype.He=function(){return d.utils.isString(this.geoResolverUrl)&&
0<d.utils.trim(this.geoResolverUrl).length};b.prototype.ej=function(d){if(null==d||0==d.length)return null;d=d.split(".");if(4!=d.length)return null;for(var e=[],b=0;b<d.length;b++){var h=parseInt(d[b]);if(isNaN(h)||0>h||255<h)return null;e.push(("0"+h.toString(16)).slice(-2))}return e.join("")};b.prototype.vm=function(){d.geo={failed:!1,result:null};d.utils.loadScriptAsync(this.geoResolverUrl);var h=this;d.utils.tryPeriodically(b.mc,function(){return h.isReady()},function(){h.onReady()},function(){h.Vc()})};
b.prototype.isReady=function(){this.ready||(this.ready=d.geo&&(d.geo.failed||null!==d.geo.result))||d.log("M217");return this.ready};b.prototype.onReady=function(){d.geo.failed?(d.log("M218"),this.Ob()&&(d.geo=this.pd())):(d.assert("object"===typeof d.geo.result),d.log("M219",d.geo.result));d.geo&&d.geo.result&&this.channel.fd(d.geo.result);this.channel.onResolverReady()};b.prototype.Vc=function(){d.log("M220");this.Ob()&&(d.geo=this.pd());d.geo&&d.geo.result&&this.channel.fd(d.geo.result);this.ready=
!0;this.channel.onResolverReady()};b.mc=function(d){return 10<d?-1:[1,50,100,500][d-1]||1E3};return b}();h.hh=a})(d.channel||(d.channel={}))})(g||(g={}));(function(d){(function(h){var a=function(){function b(){this.ready=!1;this.channel=null}b.prototype.init=function(h){this.channel=h;b.X=b.X||b.sj();this.ready=!b.X.Fb;var e=this;if(b.X.Fb)d.log("M221"),b.X.Fb.ADRUM.command("listenForOkToSendChildFrameBeacons",function(){d.log("M222");e.ready=!0;e.onReady()});else e.onReady()};b.prototype.isReady=
function(){this.isReady||d.log("M223");return this.ready};b.prototype.onReady=function(){this.channel.Sl(b.X);this.channel.onResolverReady()};b.sj=function(){for(var h=window,e,c=b.mf(h),a=window;a.parent&&!d.utils.compareWindows(a,a.parent);){a=a.parent;c=c||b.mf(a);try{a.ADRUM&&(e=e||a,h=a)}catch(g){}}return new d.Qg(e,h,c)};b.mf=function(d){try{return 0==d.document.URL.indexOf("https:")}catch(e){}};return b}();a.X=null;h.Rg=a})(d.channel||(d.channel={}))})(g||(g={}));(function(d){(function(h){var a=
function(){function b(e,c,k){this.events=[];this.ta={};this.zb=NaN;this.la=[];this.Bc=!1;this.bufferMode=d.conf.userConf&&d.conf.userConf.channel&&"undefined"!==typeof d.conf.userConf.channel.bufferMode?d.conf.userConf.channel.bufferMode:!0;this.Tb=-1;this.km=e;this.Ci=c;this.la.push(new h.hh(k));this.la.push(new h.Rg);this.la.push(new h.U)}b.create=function(){var e,c;e=b.rl();d.utils.isDefined(e)?(e=new d.beacons.jh(e),c=new d.beacons.ih):d.utils.isCORSSupported()&&!d.conf.sendImageBeacon?(e=new d.beacons.Ug,
c=new d.beacons.Tg):d.conf.neverSendImageBeacon?(e=new d.beacons.eh,c=new d.beacons.dh):(e=new d.beacons.rh,c=new d.beacons.qh);e=new b(e,c,d.conf.geoResolverUrl);e.init();return e};b.prototype.init=function(){for(var d=0;d<this.la.length;d++)this.la[d].init(this)};b.prototype.Dm=function(b){return(b.parentType===d.EventType.VPageView||b.parentType===d.EventType.NG_VIRTUAL_PAGE)&&null!==this.ta[b.parentGUID]};b.prototype.$c=function(b){var c=b.parentGUID;if(!d.utils.isDefined(this.ta[c])){this.ta[c]=
[];var h=this,k=b.eventGUID;d.utils.oSTO(function(){h.vc(k)},1E4)}this.ta[c].push(b)};b.prototype.report=function(e){e.sequenceId=d.gg.se.Aj();e.timestamp=e.timestamp||d.utils.now();this.Dm(e)?this.$c(e):this.events.push(e);1==this.events.length&&(this.zb=d.utils.now());var c=e.parentGUID;c&&c!==d.correlation.getPageGUID()||this.vc(e.eventGUID);b.yk(e)&&(this.Bc=!0);this.od()};b.prototype.vc=function(d){var b=this.ta[d];this.ta[d]=null;if(b&&0!=b.length)for(this.events=this.events.concat(b),d=0;d<
b.length;d++)this.vc(b[d].eventGUID)};b.prototype.Ck=function(b){return b.eventType===d.EventType.PageView||b.eventType===d.EventType.IFRAME};b.prototype.Di=function(){for(var b=0;b<this.events.length;b++){var c=this.events[b];if(this.Ck(c)){var h=this.X.Fb;h&&(c.parentLifecyclePhase=d.Wh.ue(h,d.lifecycle),c.parentGUID=h.ADRUM.correlation.getPageGUID(),c.parentUrl=d.utils.V.ma(h.document.URL),d.utils.isDefined(h.ADRUM.events.ja.userPageName)&&(c.nl=h.ADRUM.events.ja.userPageName),c.parentType=d.utils.compareWindows(top,
h)?d.EventType.PageView:d.EventType.IFRAME)}}};b.prototype.Pl=function(){if(0==this.events.length)d.log("M224");else{this.Di();var b=this.qd(this.events,this.X),c=this.Ci.Kb(this.events,this.rj,this.X);this.km.send(c,b);this.events=[];this.zb=Number.POSITIVE_INFINITY}};b.prototype.onResolverReady=function(){this.od()};b.prototype.fd=function(d){this.rj=d};b.prototype.Sl=function(d){this.X=d};b.prototype.addResolver=function(d){d.init(this);this.la.push(d)};b.prototype.Jl=function(){for(var d=0;d<
this.la.length;d++)if(!this.la[d].isReady())return!1;return!0};b.prototype.nf=function(){return this.zb+d.conf.Td>d.utils.now()};b.prototype.Jk=function(){return this.events.length<d.conf.wh};b.prototype.qd=function(b,c){if(c.qd||d.conf.userConf.useHTTPSAlways)return!0;for(var h=0;h<b.length;h++){var k=b[h];if(k.eventUrl&&0==k.eventUrl.indexOf("https:"))return!0}return!1};b.prototype.getEventsWithParentGUID=function(d){return this.ta[d]||[]};b.prototype.od=function(){if(this.Jl())if(this.Cm()){if(this.nf()&&
0<this.events.length&&0>this.Tb){var b=this;this.Tb=d.utils.oSTO(function(){b.od()},d.conf.Td+this.zb-d.utils.now())}}else clearTimeout(this.Tb),this.Tb=-1,this.Bc=!1,this.Pl()};b.yk=function(b){return b.eventType===d.EventType.PageView||b.eventType===d.EventType.IFRAME||b.eventType===d.EventType.VPageView};b.prototype.Cm=function(){return this.bufferMode&&!this.Bc&&this.Jk()&&this.nf()};b.sl=function(){if(d.utils.isDefined(window.webkit)&&d.utils.isDefined(window.webkit.messageHandlers)&&d.utils.isDefined(window.webkit.messageHandlers.ADEUM_js_handler)&&
d.utils.isFunction(window.webkit.messageHandlers.ADEUM_js_handler.postMessage))return window.webkit.messageHandlers.ADEUM_js_handler};b.ql=function(){if(d.utils.isDefined(window.ADEUM_js_handler)&&d.utils.isFunction(window.ADEUM_js_handler.postMessage))return window.ADEUM_js_handler};b.rl=function(){return b.ql()||b.sl()};return b}();h.Channel=a;var b=a.create();h.report=function(d){b.report(d)};h.addResolver=function(d){b.addResolver(d)};h.getEventsWithParentGUID=function(d){return b.getEventsWithParentGUID(d)}})(d.channel||
(d.channel={}))})(g||(g={}));(function(d){var h=function(){function h(){}h.Mf=function(){return window.attachEvent?d.utils.isFunction(window.addEventListener)?this.rd:this.ug:this.zg};h.Lf=function(b){var k=null;switch(h.Mf()){case h.zg:k=b.parentPhase();break;case h.rd:k=d.lifecycle.findPhaseAtNominalTime(b.getSendTime());break;case h.ug:k=null}return d.lifecycle.getPhaseID(k)};return h}();h.zg="uCT";h.rd="uNET";h.ug="tIA";d.tb=h})(g||(g={}));(function(d){(function(h){var a=d.utils.hasOwnPropertyDefined,
b=function(b){function e(){return null!==b&&b.apply(this,arguments)||this}u(e,b);e.prototype.D=function(c){var a=b.prototype.D.call(this,c,e.getContext(c)),g=c.url(),m=c.getSendTime(),n=c.getFirstByteTime(),q=c.getRespAvailTime(),t=c.getRespProcTime(),p=c.parentPhase();d.assert(null!==g&&null!==m&&null!==n&&null!==q&&null!==t,"M225",g,m,n,q,t,p);if(null===g||null===m||null===n||null===q||null===t)return null;g=c.error();m={PLC:1,FBT:n-m,DDT:q-n,DPT:t-q,PLT:t-m,ARE:g?1:0};n=c.url();if(!e.Qk(m,n))return null;
d.conf.viz&&d.utils.wc(document.getElementById(d.conf.viz),m,"xhr");d.utils.mergeJSON(a,{eventUrl:d.utils.V.ma(n),parentLifecyclePhase:c.parentPhaseId(),metrics:m,method:c.method(),timestamp:c.timestamp(),ajaxError:g&&[g.status,g.msg||""],xhrStatus:c.xhrStatus()});(c=c.parameter())&&h.aa.Uc(c,d.conf.Pa)?a.parameter=c:c&&h.aa.Ia("parameter",d.conf.Pa);a.parentType==d.EventType.VPageView&&d.conf.spa2?d.utils.hg(a,h.pb.userPageName):d.utils.hg(a,h.ja.userPageName);return a};e.getData=function(b){if(d.utils.isDefined(b)&&
d.utils.isDefined(b.data))return b.data};e.getContext=function(d){return{url:d.url()||"",method:d.method()||"",data:e.getData(d.dataObject())||""}};e.Qk=function(b,e){for(var h in b)if(a(b,h)){var k=b[h];if(0>k)return d.error("M226",h,k,e),!1}return!0};return e}(h.Ma);h.ce=b})(d.events||(d.events={}))})(g||(g={}));(function(d){(function(h){var a=function(b){function h(){return null!==b&&b.apply(this,arguments)||this}u(h,b);h.prototype.D=function(e){var h=b.prototype.D.call(this,e);h&&(e=e.allResponseHeaders()||
"",(e=d.correlation.Qj(e))&&null!==e&&null!==e.clientRequestGUID&&(h.eventGUID=e.clientRequestGUID),null!==e&&(h.serverMetadata=e));return h};return h}(h.ce);h.Lg=a})(d.events||(d.events={}))})(g||(g={}));(function(d){(function(h){var a=function(b){function k(){return null!==b&&b.apply(this,arguments)||this}u(k,b);k.prototype.D=function(e){var c=b.prototype.D.call(this,e);d.utils.mergeJSON(c,{message:e.msg()||"",timestamp:e.timestamp(),line:e.line(),stack:e.stack(),parentPageName:c.parentType==d.EventType.VPageView&&
d.conf.spa2?h.pb.userPageName:h.ja.userPageName});d.utils.isString(c.userPageName)||(c.userPageName=c.nl);return c};return k}(h.Ma);h.Vh=a})(d.events||(d.events={}))})(g||(g={}));(function(d){(function(d){(function(a){a.build=function(b){var k={},e=d.metricSpec[b.type()],c;for(c in e){var a=e[c];if(null!==a.name&&b.perf.getEntryByName(a.start)&&b.perf.getEntryByName(a.end)){b.perf.measure(a.name,a.start,a.end);var g=b.perf.getEntryByName(a.name);k[a.name]=g&&0<=g.duration&&g.duration||null}}for(c in k)k[c]=
Math.round(k[c]);return k}})(d.ec||(d.ec={}))})(d.events||(d.events={}))})(g||(g={}));(function(d){(function(d){var a=function(b){function a(){return null!==b&&b.apply(this,arguments)||this}u(a,b);a.prototype.D=function(e){var c=b.prototype.D.call(this,e),a=d.ec.build(e);a.PLC=1;c.metrics=a;c.timestamp=e.timestamp();e=(new d.ResourceTimingInfoBuilder(e.resTiming())).build();null!==e&&(c.resourceTimingInfo=e);return c};return a}(d.Ma);d.be=a})(d.events||(d.events={}))})(g||(g={}));(function(d){(function(h){var a=
function(b){function a(){return null!==b&&b.apply(this,arguments)||this}u(a,b);a.setPageName=function(d){a.na=d};a.prototype.D=function(e){var c=b.prototype.D.call(this,e),g=h.ec.build(e);g.PLT=e.timestamp()-e.startTime;g.PLC=1;c.metrics=g;c.timestamp=e.timestamp();g=(new h.ResourceTimingInfoBuilder(e.resTiming(),null,e.startTime)).build();null!==g&&(c.resourceTimingInfo=g);d.utils.isDefined(e.userPageName)&&(c.userPageName=e.userPageName);!d.utils.isDefined(c.userPageName)&&d.utils.isDefined(a.na)&&
(h.aa.ld("userPageName",a.na,d.conf.Qa)?c.userPageName=a.na:h.aa.Ia("userPageName",d.conf.Qa),a.na=void 0);return c};return a}(h.Ma);h.pb=a})(d.events||(d.events={}))})(g||(g={}));(function(d){(function(d){var a=function(d){function h(){return null!==d&&d.apply(this,arguments)||this}u(h,d);h.prototype.D=function(e){var h=d.prototype.D.call(this,e);h&&(h.metrics.VDC=e.digestCount()||0);return h};return h}(d.be);d.Rh=a})(d.events||(d.events={}))})(g||(g={}));(function(d){var h=d.events||(d.events={});
h.Tf={};d=[{Aa:h.PageView,wa:new h.ja},{Aa:h.Ajax,wa:new h.ce},{Aa:h.AdrumAjax,wa:new h.Lg},{Aa:h.Error,wa:new h.Vh},{Aa:h.VPageView,wa:new h.be},{Aa:h.AnySpaVPageView,wa:new h.pb},{Aa:d.ng.NgVPageView,wa:new h.Rh}];for(var a=0;a<d.length;a++){var b=d[a];b.Aa.prototype._regId=a;h.Tf[a]=b.wa}})(g||(g={}));(function(d){(function(h){h.reportEvent=function(h){var b=d.events.Tf[h._regId];b?(b=b.D(h),d.utils.isDefined(b)&&(d.log("M228",d.EventType[h.type()]),d.channel.report(b))):d.log("M227",d.EventType[d.eventType])}})(d.reporter||
(d.reporter={}))})(g||(g={}));(function(d){(function(h){var a=function(){function b(){this.ready=!1}b.prototype.onReady=function(){this.ready=!0;this.channel.onResolverReady()};b.prototype.isReady=function(){this.ready||d.log("M229");return this.ready};b.prototype.init=function(d){this.channel=d};return b}();h.ii=a})(d.commands||(d.commands={}))})(g||(g={}));(function(d){(function(h){var a=new h.ii;d.channel.addResolver(a);h.marks={};h.mark=function(b,a){d.log("M230",b,a);h.marks[b]=a};h.reportOnload=
function(b){d.utils.oSTO(function(){d.log("M231");d.reporter.reportEvent(b);a.onReady()},d.conf.gi)};h.reportEvent=function(){d.reporter.reportEvent.apply(d.reporter,arguments)};h.addResolver=function(b){d.channel.addResolver(b)};h.reportXhr=function(b){d.log("M232");d.tb.Mf()==d.tb.rd?(d.log("M233"),d.utils.oSTO(function(){b.parentPhaseId(d.tb.Lf(b));d.reporter.reportEvent(b)},0)):(b.parentPhaseId(d.tb.Lf(b)),d.reporter.reportEvent(b))};h.listenForOkToSendChildFrameBeacons=function(b){d.log("M234");
try{b()}catch(h){d.exception(h,"M235")}};h.reportPageError=function(b){var h=b.url();d.log("M236",b.msg(),h,b.line(),b.stack());h&&0!==h.length||b.url("CROSSORIGIN");d.reporter.reportEvent(b)};h.setPageName=function(b){d.utils.isString(b)&&0<d.utils.trim(b).length&&d.events.ja.setPageName(b)};h.setVirtualPageName=function(b){d.utils.isString(b)&&0<d.utils.trim(b).length&&d.conf.spa2&&d.events.pb.setPageName(b)};h.addUserData=function(b,h){d.events.ja.addUserData(b,h)};h.call=function(d){d()}})(d.commands||
(d.commands={}))})(g||(g={}));(function(d){(function(d){d.Be=function(a){return encodeURIComponent(d.V.gl(a))}})(d.utils||(d.utils={}))})(g||(g={}));(function(d){(function(h){var a=function(){function b(){}b.prototype.setUp=function(){this.Yk();d.utils.addEventListener(window,"pagehide",b.yd);d.utils.addEventListener(window,"beforeunload",b.yd);d.utils.addEventListener(window,"unload",b.yd)};b.prototype.Yk=function(){(this.startTime=b.nj()||b.mj())&&d.commands.mark("starttime",this.startTime)};b.nj=
function(){var b;try{if(d.utils.isDefined(window.external)&&d.utils.isNumber(window.external.pageT))b=(new Date).getTime()-window.external.pageT;else if(d.utils.isDefined(window.gtbExternal)&&d.utils.isFunction(window.gtbExternal.pageT)){var e=window.gtbExternal.pageT();d.utils.isNumber(e)&&(b=(new Date).getTime()-e)}else d.utils.isDefined(window.chrome)&&d.utils.isFunction(window.chrome.csi)&&(e=window.chrome.csi(),d.utils.isDefined(e)&&d.utils.isNumber(e.pageT)&&(b=(new Date).getTime()-e.pageT));
b&&(b=Math.round(b),d.log("M237",b))}catch(h){d.exception(h,"M238")}return b};b.mj=function(){var b=d.correlation.startTimeCookie;if(b){d.log("M239",b.startTime,b.startPage);var e=d.utils.Be(document.referrer);if(e===b.startPage)if(isNaN(b.startTime))d.log("M240",b.startTime);else return b.startTime;else d.log("M241",e,b.startPage)}else d.log("M242")};b.aj=function(b,e){var h=document.domain,a="https:"===document.location.protocol,g="ADRUM=s="+Number(new Date)+"&r="+d.utils.Be(document.location.href),
m=g+";path=/";a&&(m+=";secure");d.log("M243",g);if(!d.conf.useStrictDomainCookies){for(var a=b(),h=h.split("."),n="",q=h.length-1;0<=q;q--){n="."+h[q]+n;d.log("M244",n);e(m+";domain="+n);var t=b();if(t!=a&&0<=t.indexOf(g)){d.log("M245");d.log("M246");return}}d.log("M247")}d.log("M248");e(m);d.log("M249")};return b}();a.yd=function(){var d=!1;return function(){d||(d=!0,a.aj(function(){return document.cookie},function(d){document.cookie=d}))}}();h.Wm=a;h.dm=new a})(d.monitor||(d.monitor={}))})(g||(g=
{}));(function(d){d.log("M250");d.monitor.dm.setUp();d.q.processQ();d.initEXTDone=!0;d.log("M251")})(g||(g={}))}};})();
